"""
data_bootstrap.py — ensures runtime data files exist before the app starts.

In local dev these files are generated by the training/precompute scripts.
In a deployed container the filesystem starts empty, so we download them
on first run from a private HuggingFace Dataset.

Configuration (env vars):
  HF_DATASET_REPO — e.g., "your-username/organic-sound-artifacts"
                    The Dataset repo on the HuggingFace Hub.
  HF_TOKEN        — only needed if the dataset is private. Auto-provided
                    on HF Spaces; must be set manually on other hosts.

The function is idempotent: if the files are already on disk, it returns
immediately (no network call, no HF Hub import).
"""

import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(PROJECT_ROOT, "data")

# Runtime-essential files. Training artifacts (autoencoder.pt, scaler.pkl) are
# only needed for re-generating embeddings, not for serving recommendations,
# so we don't bootstrap them.
RUNTIME_FILES = ("embeddings.npy", "song_ids.npy", "song_metadata.pkl")


def ensure_data_files() -> None:
    os.makedirs(DATA_DIR, exist_ok=True)
    missing = [f for f in RUNTIME_FILES if not os.path.exists(os.path.join(DATA_DIR, f))]
    if not missing:
        return

    repo_id = os.getenv("HF_DATASET_REPO")
    if not repo_id:
        raise RuntimeError(
            f"Missing required data files: {missing}. "
            "Set HF_DATASET_REPO env var to fetch from the Hub, "
            "or run the local training/precompute scripts to generate them."
        )

    from huggingface_hub import hf_hub_download

    token = os.getenv("HF_TOKEN") or None
    for filename in missing:
        print(f"[bootstrap] Downloading {filename} from {repo_id}...")
        hf_hub_download(
            repo_id=repo_id,
            repo_type="dataset",
            filename=filename,
            local_dir=DATA_DIR,
            token=token,
        )
    print(f"[bootstrap] Done. {len(missing)} file(s) downloaded.")


if __name__ == "__main__":
    ensure_data_files()
