"""
recommender.py - music similarity engine

Loads the (N, 16) song embeddings generated by the autoencoder and Song ID array
and exposes a single function that takes a Spotify track ID and returns
the top-K most similar tracks based on cosine similarity in the autoencoder's
16-dimensional latent space.

This module is designed to be imported by app.py (the Flask backend).
All artifacts are loaded ONCE at import time, so per-request inference
is just a numpy matrix multiplication (~5-10ms).


"""

import os
import sys
import numpy as np

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from autoencoder import MusicAutoencoder

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(PROJECT_ROOT, 'data')
MODEL_PATH = os.path.join(DATA_DIR, 'autoencoder.pt')
EMBEDDINGS_PATH = os.path.join(DATA_DIR, 'embeddings.npy')
SONG_IDS_PATH = os.path.join(DATA_DIR, 'song_ids.npy')

print("Initializing recommender...")

# Loads the embedings (1.2M, 16)
_embeddings = np.load(EMBEDDINGS_PATH)

# Loads the corresponding Spotify track IDs (1.2M,)
_song_ids = np.load(SONG_IDS_PATH)

_id_to_index = {sid: idx for idx, sid in enumerate(_song_ids)}

# Pre-normalize embeddings to unit length (L2 norm = 1).
# Why? Cosine similarity between two vectors A and B is:
#     (A · B) / (||A|| × ||B||)
# If we make every vector unit-length up front, ||A|| and ||B|| are always 1,
# so cosine similarity collapses to just A · B (a dot product).
# This lets us compute similarity for ALL 1.2M songs at once as a single
# matrix multiplication, which numpy is heavily optimized for.

_norms = np.linalg.norm(_embeddings, axis=1, keepdims=True)
_embeddings_normalized = _embeddings / _norms


print(f"Loaded {len(_song_ids):,} songs with {_embeddings.shape[1]}-dim embeddings")
print("Recommender ready.")

def recommend(track_id: str, k: int = 10) -> list:
    """
    Return the top-K most similar songs to the given Spotify track ID.

    Args:
        track_id: Spotify track ID (e.g., "7lmeHLHBe4nmXzuXc0HDjk")
        k: number of recommendations to return (default 3)

    Returns:
        List of dicts, each with keys 'track_id' and 'similarity'.
        Sorted from most to least similar. Returns empty list if track_id
        is not in our database.

    Example:
        >>> recommend("7lmeHLHBe4nmXzuXc0HDjk", k=3)
        [{"track_id": "...", "similarity": 0.987},
         {"track_id": "...", "similarity": 0.981},
         {"track_id": "...", "similarity": 0.975}]
    """
    idx = _id_to_index.get(track_id)
    if idx is None:
        print(f"Track ID {track_id} not found in dataset.")
        return []
    
    query_vec = _embeddings_normalized[idx]

    # Compute cosine similarity as dot product (since embeddings are pre-normalized)
    similarities = _embeddings_normalized @ query_vec


    # Get indices of top-K most similar songs (excluding the query song itself)
    top_indices = np.argsort(similarities)[::-1][:k+1]



    # Build the result list, skipping the query song itself
    results = []
    for i in top_indices:
        candidate_id = _song_ids[i]
        if candidate_id == track_id:
            continue  # skip the query song
        results.append({
            "track_id": str(candidate_id),
            "similarity": float(similarities[i]),
        })
        if len(results) >= k:
            break

    return results

if __name__ == "__main__":
    import pandas as pd
    from data_utils import get_csv_path

    print("\nLoading metadata for evaluation...")
    df_meta = pd.read_csv(get_csv_path(), usecols=[
        'id', 'name', 'artists', 'tempo', 'energy', 'danceability', 'valence'
    ])
    df_meta = df_meta.set_index('id')  # makes lookup by track_id instant

    def describe(track_id):
        """Pretty-print a song's metadata."""
        try:
            row = df_meta.loc[track_id]
            return (f"{row['name']} by {row['artists']}\n"
                    f"    tempo={row['tempo']:.0f}  energy={row['energy']:.2f}  "
                    f"danceability={row['danceability']:.2f}  valence={row['valence']:.2f}")
        except KeyError:
            return f"<song {track_id} not in metadata>"

    # Test with 3 different songs to see how recommendations vary by genre/mood
    test_indices = [42, 50_000, 800_000]

    for idx in test_indices:
        test_id = str(_song_ids[idx])
        print(f"\n{'=' * 70}")
        print(f"Query: {describe(test_id)}")
        print(f"{'=' * 70}")

        recs = recommend(test_id, k=5)
        for rank, rec in enumerate(recs, 1):
            print(f"\n  Rank {rank}  (similarity: {rec['similarity']:.4f})")
            print(f"  {describe(rec['track_id'])}")